name: Keep Streamlit App Alive

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  wake-up:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: |
          npm install puppeteer
          node wakeup.js

      - name: Create wakeup.js
        run: |
          echo "const puppeteer = require('puppeteer');
          (async () => {
            const browser = await puppeteer.launch({ headless: true, args: ['--no-sandbox'] });
            const page = await browser.newPage();
            await page.goto('https://homefinder-tampa.streamlit.app/', { waitUntil: 'networkidle2' });
            await page.waitForTimeout(15000); // Wait 15 sec to simulate user activity
            await browser.close();
          })();" > wakeup.js
